/// English strings.
const Map<String, String> kStringsEn = {
  // App
  'app.name': 'NOVA',
  'app.tagline': "Kazakhstan's marketplace",

  // Bottom navigation
  'nav.home': 'Home',
  'nav.catalog': 'Catalog',
  'nav.favorites': 'Favorites',
  'nav.cart': 'Cart',
  'nav.profile': 'Profile',
  'nav.seller': 'Seller dashboard',

  // Common actions
  'action.retry': 'Retry',
  'action.cancel': 'Cancel',
  'action.close': 'Close',
  'action.save': 'Save',
  'action.continue': 'Continue',
  'action.login': 'Log in',
  'action.register': 'Sign up',
  'action.logout': 'Log out',

  // Generic states
  'state.loading': 'Loading…',
  'state.empty.title': 'Nothing here yet',
  'state.empty.body': 'Content will appear here',
  'state.error.title': 'Something went wrong',
  'state.error.body': 'Could not load the data',

  // Screen placeholders (F1)
  'screen.placeholder.badge': 'Coming in a later stage',

  // Settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.system': 'Match system',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',

  // Auth
  'auth.login.title': 'Log in',
  'auth.register.title': 'Sign up',
  'auth.field.identifier': 'Email or phone',
  'auth.field.email': 'Email',
  'auth.field.phone': 'Phone',
  'auth.field.fullName': 'Full name',
  'auth.field.password': 'Password',
  'auth.loginRequired.title': 'Sign in required',
  'auth.loginRequired.body': 'Log in to continue',

  // API error codes → user-facing copy
  'error.NETWORK_ERROR': 'No connection to the server. Check your internet.',
  'error.TIMEOUT': 'The server is taking too long. Try again.',
  'error.INVALID_CREDENTIALS': 'Wrong email/phone or password',
  'error.ACCOUNT_DISABLED': 'This account has been disabled',
  'error.SESSION_EXPIRED': 'Your session expired, please log in again',
  'error.UNAUTHORIZED': 'Sign in required',
  'error.FORBIDDEN': "You don't have permission for this action",
  'error.EMAIL_ALREADY_EXISTS': 'An account with this email already exists',
  'error.PHONE_ALREADY_EXISTS': 'An account with this phone already exists',
  'error.WEAK_PASSWORD': 'That password is too weak',
  'error.VALIDATION_ERROR': 'Please check the entered details',
  'error.INSUFFICIENT_STOCK': 'Not enough stock for this item',
  'error.OFFER_UNAVAILABLE': 'This offer is no longer available',
  'error.CART_EMPTY': 'Your cart is empty',
  'error.TOO_MANY_REQUESTS': 'Too many attempts. Please wait a moment.',
  'error.UNKNOWN_ERROR': 'Something went wrong',

  // --- Stage F2 (auth) ---
  'auth.login.subtitle': 'Sign in to your NOVA account',
  'auth.register.subtitle': 'Create your NOVA account',
  'auth.field.confirmPassword': 'Confirm password',
  'auth.action.noAccount': 'Don\'t have an account?',
  'auth.action.haveAccount': 'Already have an account?',
  'auth.action.toRegister': 'Sign up',
  'auth.action.toLogin': 'Log in',
  'auth.busy.login': 'Signing in…',
  'auth.busy.register': 'Creating account…',
  'auth.password.show': 'Show password',
  'auth.password.hide': 'Hide password',
  'auth.validation.identifierRequired': 'Enter your email or phone',
  'auth.validation.emailRequired': 'Enter your email',
  'auth.validation.emailInvalid': 'Invalid email format',
  'auth.validation.nameRequired': 'Enter your full name',
  'auth.validation.passwordRequired': 'Enter a password',
  'auth.validation.passwordTooShort': 'At least 8 characters',
  'auth.validation.passwordNeedsLetterDigit':
      'Needs at least one letter and one digit',
  'auth.validation.passwordsDontMatch': 'Passwords do not match',
  'auth.restore.failedTitle': 'Couldn\'t restore your session',
  'auth.restore.failedBody':
      'Connection problem. Check your internet and try again.',
  'seller.forbidden.title': 'Sellers only',
  'seller.forbidden.body': 'This section is for NOVA seller accounts.',

  // ---- F6A: seller dashboard ----
  'seller.dashboard.title': 'Seller dashboard',
  'seller.dashboard.quickActions': 'Quick actions',
  'seller.dashboard.noReviews': 'No reviews yet',
  'seller.metric.salesToday': 'Sales today',
  'seller.metric.ordersToday': 'Orders today',
  'seller.metric.ordersTotal': 'Total: {n}',
  'seller.metric.availableBalance': 'Available to withdraw',
  'seller.metric.pendingBalance': 'Pending',
  'seller.metric.activeOffers': 'Active offers',
  'seller.metric.lowStock': 'Low stock',
  'seller.metric.lowStockHint': '≤ {n} pcs',
  'seller.action.offers': 'Offers',
  'seller.action.inventory': 'Inventory',
  'seller.action.orders': 'Orders',
  'seller.action.finance': 'Finance',
  'seller.action.payouts': 'Payouts',
  'seller.unavailable.title': 'Seller account unavailable',
  'seller.unavailable.body':
      'Your seller account is disabled or no longer linked. '
      'Please contact NOVA support.',
  'admin.notice.title': 'Administration is web-only',
  'admin.notice.body':
      'The admin dashboard is available only in the NOVA web app.',
  'profile.role.customer': 'Customer',
  'profile.role.seller': 'Seller',
  'profile.role.admin': 'Administrator',
  'profile.section.account': 'Account',
  'profile.section.shopping': 'Shopping',
  'profile.section.preferences': 'Preferences',
  'profile.field.name': 'Name',
  'profile.field.email': 'Email',
  'profile.field.phone': 'Phone',
  'profile.field.role': 'Role',
  'profile.action.sellerDashboard': 'Seller dashboard',
  'profile.action.logout': 'Log out',
  'profile.action.logoutAll': 'Log out on all devices',
  'profile.logoutAll.confirmTitle': 'Log out everywhere?',
  'profile.logoutAll.confirmBody':
      'Every session on all devices will be ended.',
  'profile.loggedOut.title': 'You\'re not signed in',
  'profile.loggedOut.body': 'Log in to see your profile, orders and favorites.',
  'error.RATE_LIMITED': 'Too many attempts. Please wait a moment.',
  'auth.field.phoneOptional': 'Phone (optional)',

  // --- Stage F3 (catalog) ---
  'home.greeting': 'Hello!',
  'home.searchHint': 'Search products',
  'home.categories': 'Categories',
  'home.seeAll': 'See all',
  'home.promo.title': 'Next-generation technology',
  'home.promo.subtitle': 'Up to 40% off flagship electronics',
  'home.rail.forYou': 'For you',
  'home.rail.popular': 'Popular',
  'home.rail.discount': 'Deals',
  'home.rail.newest': 'New arrivals',
  'home.sectionUnavailable': 'Section temporarily unavailable',
  'catalog.title': 'Catalog',
  'catalog.searchHint': 'Search products',
  'catalog.resultsCount': '{n} products',
  'catalog.filters': 'Filters',
  'catalog.sort': 'Sort',
  'catalog.clearFilters': 'Clear filters',
  'catalog.noResults.title': 'Nothing found',
  'catalog.noResults.body': 'Try changing your query or filters',
  'catalog.loadMoreError': 'Couldn\'t load more. Tap to retry.',
  'catalog.searchNothing': 'Nothing found for "{q}"',
  'sort.title': 'Sort',
  'sort.relevance': 'Relevance',
  'sort.priceAsc': 'Price: low to high',
  'sort.priceDesc': 'Price: high to low',
  'sort.ratingDesc': 'Rating',
  'sort.newest': 'Newest',
  'sort.discountDesc': 'Biggest discount',
  'filter.title': 'Filters',
  'filter.category': 'Category',
  'filter.allCategories': 'All categories',
  'filter.brand': 'Brand',
  'filter.allBrands': 'All brands',
  'filter.brandsUnavailable': 'Brands unavailable for this selection',
  'filter.price': 'Price, ₸',
  'filter.priceFrom': 'from',
  'filter.priceTo': 'to',
  'filter.priceError': 'Minimum price is above the maximum',
  'filter.rating': 'Rating',
  'filter.ratingAny': 'Any',
  'filter.ratingN': '{n}+',
  'filter.apply': 'Show products',
  'filter.reset': 'Reset',
  'product.favoriteSoon': 'Favorites arrive in the next update',
  'product.cartSoon': 'Cart arrives in the next update',
  'product.sellersN': '{n} sellers',
  'product.deliveryToday': 'Delivery today',
  'product.deliveryTomorrow': 'Delivery tomorrow',
  'product.deliveryDays': 'Delivery in {n} days',
  'product.notFound.title': 'Product not found',
  'product.notFound.body': 'It may have been removed from sale',
  'product.toCatalog': 'To catalog',
  'product.aboutProduct': 'About',
  'product.reviews': 'Reviews',
  'product.reviewsN': 'Reviews ({n})',
  'product.offers': 'Seller offers',
  'product.offersN': 'Seller offers ({n})',
  'product.bestOffer': 'Best offer',
  'product.chooseSeller': 'Choose a seller',
  'product.moreOffers': '{n} more offers',
  'product.inStockN': 'In stock: {n} pcs',
  'product.addToCart': 'Add to cart',
  'product.buyNow': 'Buy now',
  'product.deliveryLabel': 'Delivery',
  'product.sellerLabel': 'Seller',
  'product.goToSeller': 'Visit store',
  'product.noDescription': 'No description available',
  'offer.title': 'Seller offers',
  'offer.select': 'Select',
  'offer.selected': 'Selected',
  'offer.deliveryN': 'Delivery: {n} days',
  'offer.inStockN': 'In stock: {n}',
  'review.title': 'Reviews',
  'review.empty': 'No reviews yet',
  'review.showMore': 'Show more',
  'seller.storeTitle': 'Store',
  'seller.about': 'About the store',
  'seller.products': 'Seller products',
  'seller.productsN': 'Products: {n}',
  'seller.reviewsN': 'Reviews: {n}',
  'seller.noProducts': 'This seller has no products yet',
  'seller.notFound.title': 'Store not found',
  'seller.inactive': 'This store is temporarily closed',
  'common.showMore': 'Show more',
  'error.PRODUCT_NOT_FOUND': 'Product not found',
  'error.SELLER_NOT_FOUND': 'Store not found',
  'error.CATEGORY_NOT_FOUND': 'Category not found',
  'error.NOT_FOUND': 'Not found',
  'error.INVALID_SORT': 'Invalid sort parameter',
  'error.INVALID_ID': 'Invalid identifier',

  // --- Stage F4 (customer state) ---
  'action.delete': 'Delete',
  'action.add': 'Add',
  'action.edit': 'Edit',
  'favorites.empty.title': 'No favorites yet',
  'favorites.empty.body': 'Add products to come back to them later',
  'favorites.loginRequired': 'Log in to save favorites',
  'cart.title': 'Cart',
  'cart.empty.title': 'Your cart is empty',
  'cart.empty.body': 'Browse the catalog and add some products',
  'cart.clear': 'Clear cart',
  'cart.clear.confirmTitle': 'Clear the cart?',
  'cart.clear.confirmBody': 'All items will be removed from the cart.',
  'cart.subtotal': 'Subtotal',
  'cart.checkout': 'Checkout',
  'cart.added': 'Added to cart',
  'cart.itemUnavailable': 'Item unavailable',
  'cart.removeConfirmTitle': 'Remove item?',
  'cart.removeConfirmBody': 'This item will be removed from the cart.',
  'cart.qtyLimit': 'Only {n} available',
  'cart.itemsN': '{n} items',
  'cart.lineTotal': 'Total',
  'address.title': 'Delivery addresses',
  'address.add': 'Add address',
  'address.edit': 'Edit address',
  'address.empty.title': 'No saved addresses',
  'address.empty.body': 'Add an address to check out faster',
  'address.default': 'Default',
  'address.makeDefault': 'Make default',
  'address.delete.confirmTitle': 'Delete address?',
  'address.delete.confirmBody': 'This address will be deleted.',
  'address.field.title': 'Label',
  'address.field.titleHint': 'Home, work…',
  'address.field.city': 'City',
  'address.field.street': 'Street',
  'address.field.house': 'House',
  'address.field.apartment': 'Apartment',
  'address.field.postalCode': 'Postal code',
  'address.save': 'Save',
  'address.setDefaultOnSave': 'Set as default address',
  'address.validation.cityRequired': 'Enter a city',
  'address.validation.streetRequired': 'Enter a street',
  'address.validation.houseRequired': 'Enter a house number',
  'profile.action.favorites': 'Favorites',
  'profile.action.addresses': 'Delivery addresses',
  'profile.action.orders': 'My orders',
  'error.SELLER_OFFER_NOT_FOUND': 'This offer is no longer available',
  'error.CART_ITEM_NOT_FOUND': 'Item not found in the cart',
  'error.ADDRESS_NOT_FOUND': 'Address not found',

  // ---- F5: checkout + orders ----
  'checkout.title': 'Checkout',
  'checkout.section.summary': 'Your order',
  'checkout.section.address': 'Delivery address',
  'checkout.section.payment': 'Payment method',
  'checkout.section.total': 'Total',
  'checkout.placeOrder': 'Place order',
  'checkout.processing': 'Placing your order…',
  'checkout.items': '{n} items',
  'checkout.emptyCart.title': 'Your cart is empty',
  'checkout.emptyCart.body': 'Add items to place an order',
  'checkout.noAddress.title': 'No delivery address',
  'checkout.noAddress.body': 'Add an address to continue checkout',
  'checkout.addAddress': 'Add address',
  'checkout.changeAddress': 'Change',
  'checkout.selectAddress': 'Choose a delivery address',
  'checkout.mockPaymentNotice': 'Test payment method — no real charge is made',
  'checkout.summary.subtotal': 'Items',
  'checkout.summary.delivery': 'Delivery',
  'checkout.summary.deliveryFree': 'Free',
  'checkout.summary.discount': 'Discount',
  'checkout.summary.total': 'To pay',
  'checkout.error.title': 'Could not place the order',
  'checkout.error.stock': 'One of the sellers is out of stock.',
  'checkout.error.offer': 'A seller offer is no longer available.',
  'checkout.error.address':
      'The selected address is unavailable. Pick another.',
  'checkout.error.backToCart': 'Back to cart',

  'payment.method.card': 'Bank card',
  'payment.method.kaspi': 'Kaspi',
  'payment.method.applePay': 'Apple Pay',
  'payment.method.googlePay': 'Google Pay',
  'payment.status.paid': 'Paid',
  'payment.status.pending': 'Payment pending',
  'payment.status.failed': 'Payment failed',
  'payment.status.unknown': '—',

  'order.status.newOrder': 'New',
  'order.status.confirmed': 'Confirmed',
  'order.status.paid': 'Paid',
  'order.status.processing': 'Processing',
  'order.status.shipped': 'Shipped',
  'order.status.delivered': 'Delivered',
  'order.status.cancelled': 'Cancelled',
  'order.status.returned': 'Returned',
  'order.status.unknown': '—',

  'orders.title': 'My orders',
  'orders.empty.title': 'No orders yet',
  'orders.empty.body': 'Your placed orders will show up here',
  'orders.itemsCount': '{n} items',

  'order.detail.title': 'Order',
  'order.detail.placedOn': 'Placed {date}',
  'order.detail.items': 'Order items',
  'order.detail.delivery': 'Delivery address',
  'order.detail.payment': 'Payment',
  'order.detail.perUnit': '{n} × {price}',
  'order.detail.total': 'Order total',

  'order.success.title': 'Order placed',
  'order.success.body': 'Thanks for your purchase! Order details are below.',
  'order.success.orderNumber': 'Order number',
  'order.success.total': 'Total',
  'order.success.itemCount': 'Items',
  'order.success.paymentStatus': 'Payment status',
  'order.success.viewOrder': 'View order',
  'order.success.continueShopping': 'Continue shopping',

  'error.ORDER_NOT_FOUND': 'Order not found',
  'error.INVALID_ORDER_ID': 'Invalid order number',
  'error.USER_NOT_FOUND': 'User not found',
  'error.INTERNAL_ERROR': 'Server error. Please try again later.',

  // ---- F6B: seller offers + inventory ----
  'seller.offers.title': 'Offers',
  'seller.offers.add': 'Add offer',
  'seller.offers.edit': 'Edit offer',
  'seller.offers.editUnavailable': 'Could not open the offer',
  'seller.offers.searchHint': 'Search by product or SKU',
  'seller.offers.noResults': 'Nothing found',
  'seller.offers.empty.title': 'You have no offers yet',
  'seller.offers.empty.body': 'Add an offer for a product from the catalog',
  'seller.offers.created': 'Offer added',
  'seller.offers.saved': 'Changes saved',
  'seller.offers.activate': 'Activate',
  'seller.offers.deactivate': 'Deactivate',
  'seller.offers.status.active': 'Active',
  'seller.offers.status.inactive': 'Inactive',
  'seller.offers.filter.all': 'All',
  'seller.offers.filter.active': 'Active',
  'seller.offers.filter.inactive': 'Inactive',
  'seller.offers.filter.lowStock': 'Low stock',
  'seller.offers.stockN': 'In stock: {n}',
  'seller.offers.deliveryN': 'Delivery: {n} d',
  'seller.offers.reservedN': 'Reserved: {n}',
  'seller.offers.field.sku': 'SKU',
  'seller.offers.field.price': 'Price, ₸',
  'seller.offers.field.oldPrice': 'Old price, ₸',
  'seller.offers.field.oldPriceHint':
      'Optional. Leave blank to remove the struck-through price.',
  'seller.offers.field.deliveryDays': 'Delivery time, days',
  'seller.offers.field.stock': 'Stock, pcs',
  'seller.offers.validation.productRequired': 'Choose a product',
  'seller.offers.validation.skuRequired': 'Enter a SKU',
  'seller.offers.validation.priceInvalid':
      'Enter a valid amount, e.g. 250000 or 250000.00',
  'seller.offers.validation.deliveryInvalid': 'Delivery time must be 0 or more',
  'seller.offers.validation.stockInvalid': 'Stock must be 0 or more',
  'seller.offers.productSelect.title': 'Choose a product',
  'seller.offers.productSelect.searchHint': 'Search products',
  'seller.offers.productSelect.empty': 'No products found',
  'seller.offers.productSelect.prompt':
      'Choose a catalog product to add your offer to',
  'seller.offers.productSelect.cta': 'Choose product',
  'seller.offers.productSelect.change': 'Change',

  'seller.inventory.title': 'Inventory',
  'seller.inventory.empty.title': 'No stock items',
  'seller.inventory.empty.body': 'Add offers to manage stock',
  'seller.inventory.availableN': 'Available: {n}',
  'seller.inventory.reservedN': 'Reserved: {n}',
  'seller.inventory.lowStock': 'Low stock',
  'seller.inventory.lowStockBanner': 'Low-stock items: {n}',
  'seller.inventory.edit': 'Edit',
  'seller.inventory.editTitle': 'Edit stock',
  'seller.inventory.field.available': 'Available quantity',
  'seller.inventory.reservedNote':
      '{n} pcs are in active orders and cannot be removed.',
  'seller.inventory.validation.quantity': 'Quantity must be 0 or more',

  'error.INVALID_PRICE': 'Invalid price',
  'error.INVALID_OLD_PRICE': 'Invalid old price',
  'error.INVALID_DELIVERY_DAYS': 'Invalid delivery time',
  'error.INVALID_STOCK': 'Invalid stock',
  'error.INVALID_STATUS': 'Invalid status',
  'error.SKU_ALREADY_EXISTS': 'You already have an offer with this SKU',
  'error.OFFER_NOT_FOUND': 'Offer not found',
  'error.INVALID_OFFER_ID': 'Invalid offer id',

  // ---- F6C: seller orders ----
  'seller.orders.title': 'Orders',
  'seller.orders.detailTitle': 'Order',
  'seller.orders.empty.title': 'No orders yet',
  'seller.orders.empty.body':
      'Orders containing your products will show up here',
  'seller.orders.itemsN': '{n} items',
  'seller.orders.gross': 'Your items total',
  'seller.orders.commission': 'Marketplace commission',
  'seller.orders.net': 'You receive',
  'seller.orders.items': 'Your items',
  'seller.orders.delivery': 'Delivery address',
  'seller.orders.yourLinesOnly': 'Only your items on this order are shown',
  'seller.orders.lineCommission': 'commission {v}',
  'seller.orders.lineNet': 'you get {v}',

  // ---- F6D: seller finance + payouts ----
  'seller.finance.title': 'Finance',
  'seller.finance.available': 'Available to withdraw',
  'seller.finance.availableNote': 'These funds can be withdrawn.',
  'seller.finance.pending': 'Pending',
  'seller.finance.pendingNote': 'Not released yet — cannot be withdrawn.',
  'seller.finance.breakdown': 'Breakdown',
  'seller.finance.grossSales': 'Gross sales',
  'seller.finance.commission': 'Marketplace commission',
  'seller.finance.net': 'Your net income',
  'seller.finance.paidOut': 'Paid out total',
  'seller.finance.viewPayouts': 'Payout history',

  'payout.title': 'Payouts',
  'payout.empty.title': 'No payouts yet',
  'payout.empty.body': 'Request a withdrawal of your available funds',
  'payout.availableToWithdraw': 'Available to withdraw',
  'payout.requestedOn': 'Requested {date}',
  'payout.processedOn': 'Processed {date}',
  'payout.status.pending': 'Pending',
  'payout.status.processing': 'Processing',
  'payout.status.paid': 'Paid',
  'payout.status.rejected': 'Rejected',
  'payout.status.unknown': '—',
  'payout.request.title': 'Request payout',
  'payout.request.submit': 'Request',
  'payout.request.submitted': 'Payout request submitted',
  'payout.request.field.amount': 'Amount, ₸',
  'payout.request.availableHint': 'Available: {v}',
  'payout.request.pendingNote': 'Pending funds cannot be withdrawn.',
  'payout.request.error.positive': 'Enter an amount greater than zero',
  'payout.request.error.overAvailable': 'Amount exceeds your available balance',

  'error.INSUFFICIENT_AVAILABLE_BALANCE':
      'Not enough available funds to withdraw',
};
