/// Russian strings. Keys are shared across all three language maps —
/// `AppStrings` asserts in debug that KK and EN cover exactly this key set,
/// so a new string can never ship translated in one language only.
const Map<String, String> kStringsRu = {
  // App
  'app.name': 'NOVA',
  'app.tagline': 'Маркетплейс Казахстана',

  // Bottom navigation
  'nav.home': 'Главная',
  'nav.catalog': 'Каталог',
  'nav.favorites': 'Избранное',
  'nav.cart': 'Корзина',
  'nav.profile': 'Профиль',
  'nav.seller': 'Кабинет продавца',

  // Common actions
  'action.retry': 'Повторить',
  'action.cancel': 'Отмена',
  'action.close': 'Закрыть',
  'action.save': 'Сохранить',
  'action.continue': 'Продолжить',
  'action.login': 'Войти',
  'action.register': 'Регистрация',
  'action.logout': 'Выйти',

  // Generic states
  'state.loading': 'Загрузка…',
  'state.empty.title': 'Пока ничего нет',
  'state.empty.body': 'Здесь появится контент',
  'state.error.title': 'Что-то пошло не так',
  'state.error.body': 'Не удалось загрузить данные',

  // Screen placeholders (F1)
  'screen.placeholder.badge': 'Появится на следующем этапе',

  // Settings
  'settings.title': 'Настройки',
  'settings.language': 'Язык',
  'settings.theme': 'Тема',
  'settings.theme.system': 'Как в системе',
  'settings.theme.dark': 'Тёмная',
  'settings.theme.light': 'Светлая',

  // Auth
  'auth.login.title': 'Вход',
  'auth.register.title': 'Регистрация',
  'auth.field.identifier': 'Email или телефон',
  'auth.field.email': 'Email',
  'auth.field.phone': 'Телефон',
  'auth.field.fullName': 'Имя и фамилия',
  'auth.field.password': 'Пароль',
  'auth.loginRequired.title': 'Нужен вход в аккаунт',
  'auth.loginRequired.body': 'Войдите, чтобы продолжить',

  // API error codes → user-facing copy
  'error.NETWORK_ERROR': 'Нет связи с сервером. Проверьте интернет.',
  'error.TIMEOUT': 'Сервер долго не отвечает. Попробуйте ещё раз.',
  'error.INVALID_CREDENTIALS': 'Неверный email/телефон или пароль',
  'error.ACCOUNT_DISABLED': 'Этот аккаунт отключён',
  'error.SESSION_EXPIRED': 'Сессия истекла, войдите снова',
  'error.UNAUTHORIZED': 'Требуется вход в аккаунт',
  'error.FORBIDDEN': 'Недостаточно прав для этого действия',
  'error.EMAIL_ALREADY_EXISTS': 'Аккаунт с таким email уже существует',
  'error.PHONE_ALREADY_EXISTS': 'Аккаунт с таким телефоном уже существует',
  'error.WEAK_PASSWORD': 'Пароль слишком простой',
  'error.VALIDATION_ERROR': 'Проверьте правильность данных',
  'error.INSUFFICIENT_STOCK': 'Товара не хватает на складе',
  'error.OFFER_UNAVAILABLE': 'Это предложение больше недоступно',
  'error.CART_EMPTY': 'Ваша корзина пуста',
  'error.TOO_MANY_REQUESTS': 'Слишком много попыток. Подождите немного.',
  'error.UNKNOWN_ERROR': 'Что-то пошло не так',

  // --- Stage F2 (auth) ---
  'auth.login.subtitle': 'Войдите в аккаунт NOVA',
  'auth.register.subtitle': 'Создайте аккаунт NOVA',
  'auth.field.confirmPassword': 'Повторите пароль',
  'auth.action.noAccount': 'Нет аккаунта?',
  'auth.action.haveAccount': 'Уже есть аккаунт?',
  'auth.action.toRegister': 'Зарегистрироваться',
  'auth.action.toLogin': 'Войти',
  'auth.busy.login': 'Входим…',
  'auth.busy.register': 'Создаём аккаунт…',
  'auth.password.show': 'Показать пароль',
  'auth.password.hide': 'Скрыть пароль',
  'auth.validation.identifierRequired': 'Укажите email или телефон',
  'auth.validation.emailRequired': 'Укажите email',
  'auth.validation.emailInvalid': 'Неверный формат email',
  'auth.validation.nameRequired': 'Укажите имя и фамилию',
  'auth.validation.passwordRequired': 'Введите пароль',
  'auth.validation.passwordTooShort': 'Минимум 8 символов',
  'auth.validation.passwordNeedsLetterDigit':
      'Нужны хотя бы одна буква и одна цифра',
  'auth.validation.passwordsDontMatch': 'Пароли не совпадают',
  'auth.restore.failedTitle': 'Не удалось восстановить сессию',
  'auth.restore.failedBody':
      'Проблема со связью. Проверьте интернет и повторите.',
  'seller.forbidden.title': 'Только для продавцов',
  'seller.forbidden.body': 'Этот раздел доступен аккаунтам продавца NOVA.',

  // ---- F6A: seller dashboard ----
  'seller.dashboard.title': 'Кабинет продавца',
  'seller.dashboard.quickActions': 'Быстрые действия',
  'seller.dashboard.noReviews': 'Отзывов пока нет',
  'seller.metric.salesToday': 'Продажи сегодня',
  'seller.metric.ordersToday': 'Заказы сегодня',
  'seller.metric.ordersTotal': 'Всего: {n}',
  'seller.metric.availableBalance': 'Доступно к выводу',
  'seller.metric.pendingBalance': 'В ожидании',
  'seller.metric.activeOffers': 'Активные предложения',
  'seller.metric.lowStock': 'Заканчивается',
  'seller.metric.lowStockHint': '≤ {n} шт.',
  'seller.action.offers': 'Предложения',
  'seller.action.inventory': 'Остатки',
  'seller.action.orders': 'Заказы',
  'seller.action.finance': 'Финансы',
  'seller.action.payouts': 'Выплаты',
  'seller.unavailable.title': 'Аккаунт продавца недоступен',
  'seller.unavailable.body':
      'Ваш аккаунт продавца отключён или больше не привязан. '
      'Обратитесь в поддержку NOVA.',
  'admin.notice.title': 'Администрирование в веб-версии',
  'admin.notice.body':
      'Панель администратора доступна только в веб-версии NOVA.',
  'profile.role.customer': 'Покупатель',
  'profile.role.seller': 'Продавец',
  'profile.role.admin': 'Администратор',
  'profile.section.account': 'Аккаунт',
  'profile.section.shopping': 'Покупки',
  'profile.section.preferences': 'Настройки',
  'profile.field.name': 'Имя',
  'profile.field.email': 'Email',
  'profile.field.phone': 'Телефон',
  'profile.field.role': 'Роль',
  'profile.action.sellerDashboard': 'Кабинет продавца',
  'profile.action.logout': 'Выйти',
  'profile.action.logoutAll': 'Выйти на всех устройствах',
  'profile.logoutAll.confirmTitle': 'Выйти везде?',
  'profile.logoutAll.confirmBody':
      'Все сессии на всех устройствах будут завершены.',
  'profile.loggedOut.title': 'Вы не в аккаунте',
  'profile.loggedOut.body':
      'Войдите, чтобы видеть профиль, заказы и избранное.',
  'error.RATE_LIMITED': 'Слишком много попыток. Подождите немного.',
  'auth.field.phoneOptional': 'Телефон (необязательно)',

  // --- Stage F3 (catalog) ---
  'home.greeting': 'Здравствуйте!',
  'home.searchHint': 'Поиск товаров',
  'home.categories': 'Категории',
  'home.seeAll': 'Все',
  'home.promo.title': 'Технологии нового поколения',
  'home.promo.subtitle': 'Скидки до 40% на флагманскую электронику',
  'home.rail.forYou': 'Для вас',
  'home.rail.popular': 'Популярное',
  'home.rail.discount': 'Скидки',
  'home.rail.newest': 'Новинки',
  'home.sectionUnavailable': 'Раздел временно недоступен',
  'catalog.title': 'Каталог',
  'catalog.searchHint': 'Поиск товаров',
  'catalog.resultsCount': '{n} товаров',
  'catalog.filters': 'Фильтры',
  'catalog.sort': 'Сортировка',
  'catalog.clearFilters': 'Сбросить фильтры',
  'catalog.noResults.title': 'Ничего не найдено',
  'catalog.noResults.body': 'Попробуйте изменить запрос или фильтры',
  'catalog.loadMoreError':
      'Не удалось загрузить ещё. Нажмите, чтобы повторить.',
  'catalog.searchNothing': 'По запросу «{q}» ничего не найдено',
  'sort.title': 'Сортировка',
  'sort.relevance': 'По релевантности',
  'sort.priceAsc': 'Цена: по возрастанию',
  'sort.priceDesc': 'Цена: по убыванию',
  'sort.ratingDesc': 'По рейтингу',
  'sort.newest': 'Новинки',
  'sort.discountDesc': 'Максимальная скидка',
  'filter.title': 'Фильтры',
  'filter.category': 'Категория',
  'filter.allCategories': 'Все категории',
  'filter.brand': 'Бренд',
  'filter.allBrands': 'Все бренды',
  'filter.brandsUnavailable': 'Бренды недоступны для этой выборки',
  'filter.price': 'Цена, ₸',
  'filter.priceFrom': 'от',
  'filter.priceTo': 'до',
  'filter.priceError': 'Минимальная цена больше максимальной',
  'filter.rating': 'Рейтинг',
  'filter.ratingAny': 'Любой',
  'filter.ratingN': 'от {n}',
  'filter.apply': 'Показать товары',
  'filter.reset': 'Сбросить',
  'product.favoriteSoon': 'Избранное будет доступно в следующем обновлении',
  'product.cartSoon': 'Корзина будет доступна в следующем обновлении',
  'product.sellersN': '{n} продавцов',
  'product.deliveryToday': 'Доставка сегодня',
  'product.deliveryTomorrow': 'Доставка завтра',
  'product.deliveryDays': 'Доставка {n} дн.',
  'product.notFound.title': 'Товар не найден',
  'product.notFound.body': 'Возможно, он был снят с продажи',
  'product.toCatalog': 'В каталог',
  'product.aboutProduct': 'О товаре',
  'product.reviews': 'Отзывы',
  'product.reviewsN': 'Отзывы ({n})',
  'product.offers': 'Предложения продавцов',
  'product.offersN': 'Предложения продавцов ({n})',
  'product.bestOffer': 'Лучшее предложение',
  'product.chooseSeller': 'Выбрать продавца',
  'product.moreOffers': 'Ещё {n} предложений',
  'product.inStockN': 'В наличии: {n} шт.',
  'product.addToCart': 'В корзину',
  'product.buyNow': 'Купить сейчас',
  'product.deliveryLabel': 'Доставка',
  'product.sellerLabel': 'Продавец',
  'product.goToSeller': 'Перейти в магазин',
  'product.noDescription': 'Описание отсутствует',
  'offer.title': 'Предложения продавцов',
  'offer.select': 'Выбрать',
  'offer.selected': 'Выбрано',
  'offer.deliveryN': 'Доставка: {n} дн.',
  'offer.inStockN': 'В наличии: {n}',
  'review.title': 'Отзывы',
  'review.empty': 'Пока нет отзывов',
  'review.showMore': 'Показать ещё',
  'seller.storeTitle': 'Магазин',
  'seller.about': 'О магазине',
  'seller.products': 'Товары продавца',
  'seller.productsN': 'Товаров: {n}',
  'seller.reviewsN': 'Отзывов: {n}',
  'seller.noProducts': 'У продавца пока нет товаров',
  'seller.notFound.title': 'Магазин не найден',
  'seller.inactive': 'Магазин временно не работает',
  'common.showMore': 'Показать ещё',
  'error.PRODUCT_NOT_FOUND': 'Товар не найден',
  'error.SELLER_NOT_FOUND': 'Магазин не найден',
  'error.CATEGORY_NOT_FOUND': 'Категория не найдена',
  'error.NOT_FOUND': 'Не найдено',
  'error.INVALID_SORT': 'Неверный параметр сортировки',
  'error.INVALID_ID': 'Неверный идентификатор',

  // --- Stage F4 (customer state) ---
  'action.delete': 'Удалить',
  'action.add': 'Добавить',
  'action.edit': 'Изменить',
  'favorites.empty.title': 'В избранном пока ничего нет',
  'favorites.empty.body': 'Добавляйте товары, чтобы вернуться к ним позже',
  'favorites.loginRequired': 'Войдите, чтобы добавлять в избранное',
  'cart.title': 'Корзина',
  'cart.empty.title': 'Корзина пуста',
  'cart.empty.body': 'Загляните в каталог и добавьте товары',
  'cart.clear': 'Очистить корзину',
  'cart.clear.confirmTitle': 'Очистить корзину?',
  'cart.clear.confirmBody': 'Все товары будут удалены из корзины.',
  'cart.subtotal': 'Итого',
  'cart.checkout': 'Оформить заказ',
  'cart.added': 'Добавлено в корзину',
  'cart.itemUnavailable': 'Товар недоступен',
  'cart.removeConfirmTitle': 'Удалить товар?',
  'cart.removeConfirmBody': 'Товар будет удалён из корзины.',
  'cart.qtyLimit': 'Доступно только {n} шт.',
  'cart.itemsN': '{n} товаров',
  'cart.lineTotal': 'Сумма',
  'address.title': 'Адреса доставки',
  'address.add': 'Добавить адрес',
  'address.edit': 'Изменить адрес',
  'address.empty.title': 'Нет сохранённых адресов',
  'address.empty.body': 'Добавьте адрес, чтобы быстрее оформлять заказы',
  'address.default': 'Основной',
  'address.makeDefault': 'Сделать основным',
  'address.delete.confirmTitle': 'Удалить адрес?',
  'address.delete.confirmBody': 'Этот адрес будет удалён.',
  'address.field.title': 'Название',
  'address.field.titleHint': 'Дом, работа…',
  'address.field.city': 'Город',
  'address.field.street': 'Улица',
  'address.field.house': 'Дом',
  'address.field.apartment': 'Квартира',
  'address.field.postalCode': 'Индекс',
  'address.save': 'Сохранить',
  'address.setDefaultOnSave': 'Сделать основным адресом',
  'address.validation.cityRequired': 'Укажите город',
  'address.validation.streetRequired': 'Укажите улицу',
  'address.validation.houseRequired': 'Укажите дом',
  'profile.action.favorites': 'Избранное',
  'profile.action.addresses': 'Адреса доставки',
  'profile.action.orders': 'Мои заказы',
  'error.SELLER_OFFER_NOT_FOUND': 'Это предложение больше недоступно',
  'error.CART_ITEM_NOT_FOUND': 'Товар не найден в корзине',
  'error.ADDRESS_NOT_FOUND': 'Адрес не найден',

  // ---- F5: checkout + orders ----
  'checkout.title': 'Оформление заказа',
  'checkout.section.summary': 'Ваш заказ',
  'checkout.section.address': 'Адрес доставки',
  'checkout.section.payment': 'Способ оплаты',
  'checkout.section.total': 'Итого',
  'checkout.placeOrder': 'Оформить заказ',
  'checkout.processing': 'Оформляем заказ…',
  'checkout.items': '{n} товаров',
  'checkout.emptyCart.title': 'Корзина пуста',
  'checkout.emptyCart.body': 'Добавьте товары, чтобы оформить заказ',
  'checkout.noAddress.title': 'Нет адреса доставки',
  'checkout.noAddress.body': 'Добавьте адрес, чтобы продолжить оформление',
  'checkout.addAddress': 'Добавить адрес',
  'checkout.changeAddress': 'Изменить',
  'checkout.selectAddress': 'Выберите адрес доставки',
  'checkout.mockPaymentNotice':
      'Тестовый способ оплаты — реальное списание не производится',
  'checkout.summary.subtotal': 'Товары',
  'checkout.summary.delivery': 'Доставка',
  'checkout.summary.deliveryFree': 'Бесплатно',
  'checkout.summary.discount': 'Скидка',
  'checkout.summary.total': 'К оплате',
  'checkout.error.title': 'Не удалось оформить заказ',
  'checkout.error.stock': 'Недостаточно товара у одного из продавцов.',
  'checkout.error.offer': 'Предложение продавца больше недоступно.',
  'checkout.error.address': 'Выбранный адрес недоступен. Выберите другой.',
  'checkout.error.backToCart': 'Вернуться в корзину',

  'payment.method.card': 'Банковская карта',
  'payment.method.kaspi': 'Kaspi',
  'payment.method.applePay': 'Apple Pay',
  'payment.method.googlePay': 'Google Pay',
  'payment.status.paid': 'Оплачено',
  'payment.status.pending': 'Ожидает оплаты',
  'payment.status.failed': 'Ошибка оплаты',
  'payment.status.unknown': '—',

  'order.status.newOrder': 'Новый',
  'order.status.confirmed': 'Подтверждён',
  'order.status.paid': 'Оплачен',
  'order.status.processing': 'В обработке',
  'order.status.shipped': 'Отправлен',
  'order.status.delivered': 'Доставлен',
  'order.status.cancelled': 'Отменён',
  'order.status.returned': 'Возврат',
  'order.status.unknown': '—',

  'orders.title': 'Мои заказы',
  'orders.empty.title': 'Заказов пока нет',
  'orders.empty.body': 'Здесь появятся ваши оформленные заказы',
  'orders.itemsCount': '{n} тов.',

  'order.detail.title': 'Заказ',
  'order.detail.placedOn': 'Оформлен {date}',
  'order.detail.items': 'Состав заказа',
  'order.detail.delivery': 'Адрес доставки',
  'order.detail.payment': 'Оплата',
  'order.detail.perUnit': '{n} × {price}',
  'order.detail.total': 'Итого по заказу',

  'order.success.title': 'Заказ оформлен',
  'order.success.body': 'Спасибо за покупку! Детали заказа — ниже.',
  'order.success.orderNumber': 'Номер заказа',
  'order.success.total': 'Сумма',
  'order.success.itemCount': 'Товаров',
  'order.success.paymentStatus': 'Статус оплаты',
  'order.success.viewOrder': 'Посмотреть заказ',
  'order.success.continueShopping': 'Продолжить покупки',

  'error.ORDER_NOT_FOUND': 'Заказ не найден',
  'error.INVALID_ORDER_ID': 'Неверный номер заказа',
  'error.USER_NOT_FOUND': 'Пользователь не найден',
  'error.INTERNAL_ERROR': 'Ошибка сервера. Попробуйте позже.',

  // ---- F6B: seller offers + inventory ----
  'seller.offers.title': 'Предложения',
  'seller.offers.add': 'Добавить предложение',
  'seller.offers.edit': 'Изменить предложение',
  'seller.offers.editUnavailable': 'Не удалось открыть предложение',
  'seller.offers.searchHint': 'Поиск по товару или SKU',
  'seller.offers.noResults': 'Ничего не найдено',
  'seller.offers.empty.title': 'У вас пока нет предложений',
  'seller.offers.empty.body': 'Добавьте предложение к товару из каталога',
  'seller.offers.created': 'Предложение добавлено',
  'seller.offers.saved': 'Изменения сохранены',
  'seller.offers.activate': 'Активировать',
  'seller.offers.deactivate': 'Деактивировать',
  'seller.offers.status.active': 'Активно',
  'seller.offers.status.inactive': 'Неактивно',
  'seller.offers.filter.all': 'Все',
  'seller.offers.filter.active': 'Активные',
  'seller.offers.filter.inactive': 'Неактивные',
  'seller.offers.filter.lowStock': 'Заканчивается',
  'seller.offers.stockN': 'В наличии: {n}',
  'seller.offers.deliveryN': 'Доставка: {n} дн.',
  'seller.offers.reservedN': 'В резерве: {n}',
  'seller.offers.field.sku': 'SKU (артикул)',
  'seller.offers.field.price': 'Цена, ₸',
  'seller.offers.field.oldPrice': 'Старая цена, ₸',
  'seller.offers.field.oldPriceHint':
      'Необязательно. Оставьте пустым, чтобы убрать зачёркнутую цену.',
  'seller.offers.field.deliveryDays': 'Срок доставки, дней',
  'seller.offers.field.stock': 'Остаток, шт.',
  'seller.offers.validation.productRequired': 'Выберите товар',
  'seller.offers.validation.skuRequired': 'Укажите SKU',
  'seller.offers.validation.priceInvalid':
      'Введите корректную сумму, например 250000 или 250000.00',
  'seller.offers.validation.deliveryInvalid': 'Срок доставки — 0 или больше',
  'seller.offers.validation.stockInvalid': 'Остаток — 0 или больше',
  'seller.offers.productSelect.title': 'Выбор товара',
  'seller.offers.productSelect.searchHint': 'Поиск товара',
  'seller.offers.productSelect.empty': 'Товары не найдены',
  'seller.offers.productSelect.prompt':
      'Выберите товар из каталога, к которому добавите предложение',
  'seller.offers.productSelect.cta': 'Выбрать товар',
  'seller.offers.productSelect.change': 'Изменить',

  'seller.inventory.title': 'Остатки',
  'seller.inventory.empty.title': 'Нет позиций на складе',
  'seller.inventory.empty.body':
      'Добавьте предложения, чтобы управлять остатками',
  'seller.inventory.availableN': 'Доступно: {n}',
  'seller.inventory.reservedN': 'В резерве: {n}',
  'seller.inventory.lowStock': 'Заканчивается',
  'seller.inventory.lowStockBanner': 'Заканчивается позиций: {n}',
  'seller.inventory.edit': 'Изменить',
  'seller.inventory.editTitle': 'Изменить остаток',
  'seller.inventory.field.available': 'Доступное количество',
  'seller.inventory.reservedNote':
      '{n} шт. в активных заказах — их нельзя убрать.',
  'seller.inventory.validation.quantity': 'Количество — 0 или больше',

  'error.INVALID_PRICE': 'Некорректная цена',
  'error.INVALID_OLD_PRICE': 'Некорректная старая цена',
  'error.INVALID_DELIVERY_DAYS': 'Некорректный срок доставки',
  'error.INVALID_STOCK': 'Некорректный остаток',
  'error.INVALID_STATUS': 'Некорректный статус',
  'error.SKU_ALREADY_EXISTS': 'У вас уже есть предложение с таким SKU',
  'error.OFFER_NOT_FOUND': 'Предложение не найдено',
  'error.INVALID_OFFER_ID': 'Неверный идентификатор предложения',

  // ---- F6C: seller orders ----
  'seller.orders.title': 'Заказы',
  'seller.orders.detailTitle': 'Заказ',
  'seller.orders.empty.title': 'Пока нет заказов',
  'seller.orders.empty.body': 'Здесь появятся заказы с вашими товарами',
  'seller.orders.itemsN': '{n} поз.',
  'seller.orders.gross': 'Сумма ваших позиций',
  'seller.orders.commission': 'Комиссия маркетплейса',
  'seller.orders.net': 'К зачислению',
  'seller.orders.items': 'Ваши позиции',
  'seller.orders.delivery': 'Адрес доставки',
  'seller.orders.yourLinesOnly': 'Показаны только ваши позиции этого заказа',
  'seller.orders.lineCommission': 'комиссия {v}',
  'seller.orders.lineNet': 'вам {v}',

  // ---- F6D: seller finance + payouts ----
  'seller.finance.title': 'Финансы',
  'seller.finance.available': 'Доступно к выводу',
  'seller.finance.availableNote': 'Эти средства можно вывести.',
  'seller.finance.pending': 'В ожидании',
  'seller.finance.pendingNote': 'Ещё не разблокировано — вывести нельзя.',
  'seller.finance.breakdown': 'Расчёт',
  'seller.finance.grossSales': 'Продажи (брутто)',
  'seller.finance.commission': 'Комиссия маркетплейса',
  'seller.finance.net': 'Ваш доход (нетто)',
  'seller.finance.paidOut': 'Выведено всего',
  'seller.finance.viewPayouts': 'История выплат',

  'payout.title': 'Выплаты',
  'payout.empty.title': 'Выплат пока нет',
  'payout.empty.body': 'Запросите вывод доступных средств',
  'payout.availableToWithdraw': 'Доступно к выводу',
  'payout.requestedOn': 'Запрошено {date}',
  'payout.processedOn': 'Обработано {date}',
  'payout.status.pending': 'Ожидает',
  'payout.status.processing': 'В обработке',
  'payout.status.paid': 'Выплачено',
  'payout.status.rejected': 'Отклонено',
  'payout.status.unknown': '—',
  'payout.request.title': 'Запросить выплату',
  'payout.request.submit': 'Запросить',
  'payout.request.submitted': 'Запрос на выплату отправлен',
  'payout.request.field.amount': 'Сумма, ₸',
  'payout.request.availableHint': 'Доступно: {v}',
  'payout.request.pendingNote': 'Средства в ожидании вывести нельзя.',
  'payout.request.error.positive': 'Введите сумму больше нуля',
  'payout.request.error.overAvailable': 'Сумма превышает доступный баланс',

  'error.INSUFFICIENT_AVAILABLE_BALANCE':
      'Недостаточно доступных средств для вывода',
};
