/// Kazakh strings. Full coverage — no intentional fallback to Russian for
/// any key (Stage F1 §54).
const Map<String, String> kStringsKk = {
  // App
  'app.name': 'NOVA',
  'app.tagline': 'Қазақстан маркетплейсі',

  // Bottom navigation
  'nav.home': 'Басты бет',
  'nav.catalog': 'Каталог',
  'nav.favorites': 'Таңдаулылар',
  'nav.cart': 'Себет',
  'nav.profile': 'Профиль',
  'nav.seller': 'Сатушы кабинеті',

  // Common actions
  'action.retry': 'Қайталау',
  'action.cancel': 'Бас тарту',
  'action.close': 'Жабу',
  'action.save': 'Сақтау',
  'action.continue': 'Жалғастыру',
  'action.login': 'Кіру',
  'action.register': 'Тіркелу',
  'action.logout': 'Шығу',

  // Generic states
  'state.loading': 'Жүктелуде…',
  'state.empty.title': 'Әзірге түк жоқ',
  'state.empty.body': 'Мұнда мазмұн пайда болады',
  'state.error.title': 'Бірдеңе дұрыс болмады',
  'state.error.body': 'Деректерді жүктеу мүмкін болмады',

  // Screen placeholders (F1)
  'screen.placeholder.badge': 'Келесі кезеңде қосылады',

  // Settings
  'settings.title': 'Баптаулар',
  'settings.language': 'Тіл',
  'settings.theme': 'Тақырып',
  'settings.theme.system': 'Жүйе бойынша',
  'settings.theme.dark': 'Қараңғы',
  'settings.theme.light': 'Ашық',

  // Auth
  'auth.login.title': 'Кіру',
  'auth.register.title': 'Тіркелу',
  'auth.field.identifier': 'Email немесе телефон',
  'auth.field.email': 'Email',
  'auth.field.phone': 'Телефон',
  'auth.field.fullName': 'Аты-жөні',
  'auth.field.password': 'Құпия сөз',
  'auth.loginRequired.title': 'Аккаунтқа кіру қажет',
  'auth.loginRequired.body': 'Жалғастыру үшін кіріңіз',

  // API error codes → user-facing copy
  'error.NETWORK_ERROR': 'Сервермен байланыс жоқ. Интернетті тексеріңіз.',
  'error.TIMEOUT': 'Сервер ұзақ жауап бермей жатыр. Қайталап көріңіз.',
  'error.INVALID_CREDENTIALS': 'Email/телефон немесе құпия сөз қате',
  'error.ACCOUNT_DISABLED': 'Бұл аккаунт өшірілген',
  'error.SESSION_EXPIRED': 'Сеанс аяқталды, қайта кіріңіз',
  'error.UNAUTHORIZED': 'Аккаунтқа кіру қажет',
  'error.FORBIDDEN': 'Бұл әрекетке рұқсат жеткіліксіз',
  'error.EMAIL_ALREADY_EXISTS': 'Мұндай email-мен аккаунт бұрыннан бар',
  'error.PHONE_ALREADY_EXISTS': 'Мұндай телефонмен аккаунт бұрыннан бар',
  'error.WEAK_PASSWORD': 'Құпия сөз тым қарапайым',
  'error.VALIDATION_ERROR': 'Деректердің дұрыстығын тексеріңіз',
  'error.INSUFFICIENT_STOCK': 'Қоймада тауар жеткіліксіз',
  'error.OFFER_UNAVAILABLE': 'Бұл ұсыныс енді қолжетімді емес',
  'error.CART_EMPTY': 'Себетіңіз бос',
  'error.TOO_MANY_REQUESTS': 'Тым көп әрекет. Сәл күте тұрыңыз.',
  'error.UNKNOWN_ERROR': 'Бірдеңе дұрыс болмады',

  // --- Stage F2 (auth) ---
  'auth.login.subtitle': 'NOVA аккаунтына кіріңіз',
  'auth.register.subtitle': 'NOVA аккаунтын жасаңыз',
  'auth.field.confirmPassword': 'Құпия сөзді қайталаңыз',
  'auth.action.noAccount': 'Аккаунт жоқ па?',
  'auth.action.haveAccount': 'Аккаунт бар ма?',
  'auth.action.toRegister': 'Тіркелу',
  'auth.action.toLogin': 'Кіру',
  'auth.busy.login': 'Кіріп жатырмыз…',
  'auth.busy.register': 'Аккаунт жасалуда…',
  'auth.password.show': 'Құпия сөзді көрсету',
  'auth.password.hide': 'Құпия сөзді жасыру',
  'auth.validation.identifierRequired': 'Email немесе телефон енгізіңіз',
  'auth.validation.emailRequired': 'Email енгізіңіз',
  'auth.validation.emailInvalid': 'Email пішімі қате',
  'auth.validation.nameRequired': 'Аты-жөніңізді енгізіңіз',
  'auth.validation.passwordRequired': 'Құпия сөзді енгізіңіз',
  'auth.validation.passwordTooShort': 'Кемінде 8 таңба',
  'auth.validation.passwordNeedsLetterDigit':
      'Кемінде бір әріп пен бір сан керек',
  'auth.validation.passwordsDontMatch': 'Құпия сөздер сәйкес келмейді',
  'auth.restore.failedTitle': 'Сеансты қалпына келтіру мүмкін болмады',
  'auth.restore.failedBody':
      'Байланыс мәселесі. Интернетті тексеріп, қайталаңыз.',
  'seller.forbidden.title': 'Тек сатушыларға арналған',
  'seller.forbidden.body': 'Бұл бөлім NOVA сатушы аккаунттарына қолжетімді.',

  // ---- F6A: seller dashboard ----
  'seller.dashboard.title': 'Сатушы кабинеті',
  'seller.dashboard.quickActions': 'Жылдам әрекеттер',
  'seller.dashboard.noReviews': 'Әзірге пікір жоқ',
  'seller.metric.salesToday': 'Бүгінгі сатылымдар',
  'seller.metric.ordersToday': 'Бүгінгі тапсырыстар',
  'seller.metric.ordersTotal': 'Барлығы: {n}',
  'seller.metric.availableBalance': 'Шығаруға қолжетімді',
  'seller.metric.pendingBalance': 'Күтуде',
  'seller.metric.activeOffers': 'Белсенді ұсыныстар',
  'seller.metric.lowStock': 'Азайып барады',
  'seller.metric.lowStockHint': '≤ {n} дана',
  'seller.action.offers': 'Ұсыныстар',
  'seller.action.inventory': 'Қалдықтар',
  'seller.action.orders': 'Тапсырыстар',
  'seller.action.finance': 'Қаржы',
  'seller.action.payouts': 'Төлемдер',
  'seller.unavailable.title': 'Сатушы аккаунты қолжетімді емес',
  'seller.unavailable.body':
      'Сатушы аккаунтыңыз өшірілген немесе енді байланыстырылмаған. '
      'NOVA қолдау қызметіне хабарласыңыз.',
  'admin.notice.title': 'Әкімшілік — веб-нұсқада',
  'admin.notice.body': 'Әкімші панелі тек NOVA веб-нұсқасында қолжетімді.',
  'profile.role.customer': 'Сатып алушы',
  'profile.role.seller': 'Сатушы',
  'profile.role.admin': 'Әкімші',
  'profile.section.account': 'Аккаунт',
  'profile.section.shopping': 'Сатып алулар',
  'profile.section.preferences': 'Баптаулар',
  'profile.field.name': 'Аты',
  'profile.field.email': 'Email',
  'profile.field.phone': 'Телефон',
  'profile.field.role': 'Рөл',
  'profile.action.sellerDashboard': 'Сатушы кабинеті',
  'profile.action.logout': 'Шығу',
  'profile.action.logoutAll': 'Барлық құрылғыдан шығу',
  'profile.logoutAll.confirmTitle': 'Барлық жерден шығу керек пе?',
  'profile.logoutAll.confirmBody':
      'Барлық құрылғыдағы барлық сеанстар аяқталады.',
  'profile.loggedOut.title': 'Сіз аккаунтта емессіз',
  'profile.loggedOut.body':
      'Профиль, тапсырыстар мен таңдаулыларды көру үшін кіріңіз.',
  'error.RATE_LIMITED': 'Тым көп әрекет. Сәл күте тұрыңыз.',
  'auth.field.phoneOptional': 'Телефон (міндетті емес)',

  // --- Stage F3 (catalog) ---
  'home.greeting': 'Сәлеметсіз бе!',
  'home.searchHint': 'Тауарларды іздеу',
  'home.categories': 'Санаттар',
  'home.seeAll': 'Барлығы',
  'home.promo.title': 'Жаңа буын технологиялары',
  'home.promo.subtitle': 'Флагмандық электроникаға 40%-ға дейін жеңілдік',
  'home.rail.forYou': 'Сізге арналған',
  'home.rail.popular': 'Танымал',
  'home.rail.discount': 'Жеңілдіктер',
  'home.rail.newest': 'Жаңалықтар',
  'home.sectionUnavailable': 'Бөлім уақытша қолжетімді емес',
  'catalog.title': 'Каталог',
  'catalog.searchHint': 'Тауарларды іздеу',
  'catalog.resultsCount': '{n} тауар',
  'catalog.filters': 'Сүзгілер',
  'catalog.sort': 'Сұрыптау',
  'catalog.clearFilters': 'Сүзгілерді тазалау',
  'catalog.noResults.title': 'Ештеңе табылмады',
  'catalog.noResults.body': 'Сұранысты немесе сүзгілерді өзгертіп көріңіз',
  'catalog.loadMoreError': 'Тағы жүктеу мүмкін болмады. Қайталау үшін басыңыз.',
  'catalog.searchNothing': '«{q}» сұранысы бойынша ештеңе табылмады',
  'sort.title': 'Сұрыптау',
  'sort.relevance': 'Өзектілігі бойынша',
  'sort.priceAsc': 'Бағасы: өсу ретімен',
  'sort.priceDesc': 'Бағасы: кему ретімен',
  'sort.ratingDesc': 'Рейтинг бойынша',
  'sort.newest': 'Жаңалықтар',
  'sort.discountDesc': 'Ең жоғары жеңілдік',
  'filter.title': 'Сүзгілер',
  'filter.category': 'Санат',
  'filter.allCategories': 'Барлық санаттар',
  'filter.brand': 'Бренд',
  'filter.allBrands': 'Барлық брендтер',
  'filter.brandsUnavailable': 'Бұл таңдау үшін брендтер қолжетімді емес',
  'filter.price': 'Бағасы, ₸',
  'filter.priceFrom': 'бастап',
  'filter.priceTo': 'дейін',
  'filter.priceError': 'Ең төмен баға ең жоғарыдан үлкен',
  'filter.rating': 'Рейтинг',
  'filter.ratingAny': 'Кез келген',
  'filter.ratingN': '{n} бастап',
  'filter.apply': 'Тауарларды көрсету',
  'filter.reset': 'Тазалау',
  'product.favoriteSoon': 'Таңдаулылар келесі жаңартуда қолжетімді болады',
  'product.cartSoon': 'Себет келесі жаңартуда қолжетімді болады',
  'product.sellersN': '{n} сатушы',
  'product.deliveryToday': 'Бүгін жеткізу',
  'product.deliveryTomorrow': 'Ертең жеткізу',
  'product.deliveryDays': 'Жеткізу {n} күн',
  'product.notFound.title': 'Тауар табылмады',
  'product.notFound.body': 'Ол сатылымнан алынған болуы мүмкін',
  'product.toCatalog': 'Каталогқа',
  'product.aboutProduct': 'Тауар туралы',
  'product.reviews': 'Пікірлер',
  'product.reviewsN': 'Пікірлер ({n})',
  'product.offers': 'Сатушылар ұсыныстары',
  'product.offersN': 'Сатушылар ұсыныстары ({n})',
  'product.bestOffer': 'Ең жақсы ұсыныс',
  'product.chooseSeller': 'Сатушыны таңдау',
  'product.moreOffers': 'Тағы {n} ұсыныс',
  'product.inStockN': 'Қоймада: {n} дана',
  'product.addToCart': 'Себетке',
  'product.buyNow': 'Қазір сатып алу',
  'product.deliveryLabel': 'Жеткізу',
  'product.sellerLabel': 'Сатушы',
  'product.goToSeller': 'Дүкенге өту',
  'product.noDescription': 'Сипаттама жоқ',
  'offer.title': 'Сатушылар ұсыныстары',
  'offer.select': 'Таңдау',
  'offer.selected': 'Таңдалды',
  'offer.deliveryN': 'Жеткізу: {n} күн',
  'offer.inStockN': 'Қоймада: {n}',
  'review.title': 'Пікірлер',
  'review.empty': 'Әзірге пікір жоқ',
  'review.showMore': 'Тағы көрсету',
  'seller.storeTitle': 'Дүкен',
  'seller.about': 'Дүкен туралы',
  'seller.products': 'Сатушы тауарлары',
  'seller.productsN': 'Тауарлар: {n}',
  'seller.reviewsN': 'Пікірлер: {n}',
  'seller.noProducts': 'Сатушыда әзірге тауар жоқ',
  'seller.notFound.title': 'Дүкен табылмады',
  'seller.inactive': 'Дүкен уақытша жұмыс істемейді',
  'common.showMore': 'Тағы көрсету',
  'error.PRODUCT_NOT_FOUND': 'Тауар табылмады',
  'error.SELLER_NOT_FOUND': 'Дүкен табылмады',
  'error.CATEGORY_NOT_FOUND': 'Санат табылмады',
  'error.NOT_FOUND': 'Табылмады',
  'error.INVALID_SORT': 'Сұрыптау параметрі қате',
  'error.INVALID_ID': 'Идентификатор қате',

  // --- Stage F4 (customer state) ---
  'action.delete': 'Жою',
  'action.add': 'Қосу',
  'action.edit': 'Өзгерту',
  'favorites.empty.title': 'Таңдаулыларда әзірге түк жоқ',
  'favorites.empty.body': 'Кейін оралу үшін тауарларды қосыңыз',
  'favorites.loginRequired': 'Таңдаулыға қосу үшін кіріңіз',
  'cart.title': 'Себет',
  'cart.empty.title': 'Себет бос',
  'cart.empty.body': 'Каталогқа кіріп, тауарларды қосыңыз',
  'cart.clear': 'Себетті тазалау',
  'cart.clear.confirmTitle': 'Себетті тазалау керек пе?',
  'cart.clear.confirmBody': 'Барлық тауарлар себеттен жойылады.',
  'cart.subtotal': 'Барлығы',
  'cart.checkout': 'Тапсырысты рәсімдеу',
  'cart.added': 'Себетке қосылды',
  'cart.itemUnavailable': 'Тауар қолжетімді емес',
  'cart.removeConfirmTitle': 'Тауарды жою керек пе?',
  'cart.removeConfirmBody': 'Тауар себеттен жойылады.',
  'cart.qtyLimit': 'Тек {n} дана қолжетімді',
  'cart.itemsN': '{n} тауар',
  'cart.lineTotal': 'Сомасы',
  'address.title': 'Жеткізу мекенжайлары',
  'address.add': 'Мекенжай қосу',
  'address.edit': 'Мекенжайды өзгерту',
  'address.empty.title': 'Сақталған мекенжайлар жоқ',
  'address.empty.body': 'Тапсырысты жылдам рәсімдеу үшін мекенжай қосыңыз',
  'address.default': 'Негізгі',
  'address.makeDefault': 'Негізгі ету',
  'address.delete.confirmTitle': 'Мекенжайды жою керек пе?',
  'address.delete.confirmBody': 'Бұл мекенжай жойылады.',
  'address.field.title': 'Атауы',
  'address.field.titleHint': 'Үй, жұмыс…',
  'address.field.city': 'Қала',
  'address.field.street': 'Көше',
  'address.field.house': 'Үй',
  'address.field.apartment': 'Пәтер',
  'address.field.postalCode': 'Индекс',
  'address.save': 'Сақтау',
  'address.setDefaultOnSave': 'Негізгі мекенжай ету',
  'address.validation.cityRequired': 'Қаланы көрсетіңіз',
  'address.validation.streetRequired': 'Көшені көрсетіңіз',
  'address.validation.houseRequired': 'Үйді көрсетіңіз',
  'profile.action.favorites': 'Таңдаулылар',
  'profile.action.addresses': 'Жеткізу мекенжайлары',
  'profile.action.orders': 'Менің тапсырыстарым',
  'error.SELLER_OFFER_NOT_FOUND': 'Бұл ұсыныс енді қолжетімді емес',
  'error.CART_ITEM_NOT_FOUND': 'Тауар себетте табылмады',
  'error.ADDRESS_NOT_FOUND': 'Мекенжай табылмады',

  // ---- F5: checkout + orders ----
  'checkout.title': 'Тапсырысты рәсімдеу',
  'checkout.section.summary': 'Сіздің тапсырысыңыз',
  'checkout.section.address': 'Жеткізу мекенжайы',
  'checkout.section.payment': 'Төлеу тәсілі',
  'checkout.section.total': 'Барлығы',
  'checkout.placeOrder': 'Тапсырысты рәсімдеу',
  'checkout.processing': 'Тапсырыс рәсімделуде…',
  'checkout.items': '{n} тауар',
  'checkout.emptyCart.title': 'Себет бос',
  'checkout.emptyCart.body': 'Тапсырыс беру үшін тауар қосыңыз',
  'checkout.noAddress.title': 'Жеткізу мекенжайы жоқ',
  'checkout.noAddress.body': 'Жалғастыру үшін мекенжай қосыңыз',
  'checkout.addAddress': 'Мекенжай қосу',
  'checkout.changeAddress': 'Өзгерту',
  'checkout.selectAddress': 'Жеткізу мекенжайын таңдаңыз',
  'checkout.mockPaymentNotice': 'Сынақ төлеу тәсілі — нақты ақша алынбайды',
  'checkout.summary.subtotal': 'Тауарлар',
  'checkout.summary.delivery': 'Жеткізу',
  'checkout.summary.deliveryFree': 'Тегін',
  'checkout.summary.discount': 'Жеңілдік',
  'checkout.summary.total': 'Төлеуге',
  'checkout.error.title': 'Тапсырысты рәсімдеу мүмкін болмады',
  'checkout.error.stock': 'Сатушылардың бірінде тауар жеткіліксіз.',
  'checkout.error.offer': 'Сатушының ұсынысы енді қолжетімді емес.',
  'checkout.error.address':
      'Таңдалған мекенжай қолжетімді емес. Басқасын таңдаңыз.',
  'checkout.error.backToCart': 'Себетке оралу',

  'payment.method.card': 'Банк картасы',
  'payment.method.kaspi': 'Kaspi',
  'payment.method.applePay': 'Apple Pay',
  'payment.method.googlePay': 'Google Pay',
  'payment.status.paid': 'Төленді',
  'payment.status.pending': 'Төлем күтілуде',
  'payment.status.failed': 'Төлем қатесі',
  'payment.status.unknown': '—',

  'order.status.newOrder': 'Жаңа',
  'order.status.confirmed': 'Расталды',
  'order.status.paid': 'Төленді',
  'order.status.processing': 'Өңделуде',
  'order.status.shipped': 'Жіберілді',
  'order.status.delivered': 'Жеткізілді',
  'order.status.cancelled': 'Бас тартылды',
  'order.status.returned': 'Қайтарылды',
  'order.status.unknown': '—',

  'orders.title': 'Менің тапсырыстарым',
  'orders.empty.title': 'Әзірге тапсырыс жоқ',
  'orders.empty.body': 'Мұнда рәсімделген тапсырыстарыңыз көрінеді',
  'orders.itemsCount': '{n} тау.',

  'order.detail.title': 'Тапсырыс',
  'order.detail.placedOn': '{date} рәсімделді',
  'order.detail.items': 'Тапсырыс құрамы',
  'order.detail.delivery': 'Жеткізу мекенжайы',
  'order.detail.payment': 'Төлем',
  'order.detail.perUnit': '{n} × {price}',
  'order.detail.total': 'Тапсырыс бойынша барлығы',

  'order.success.title': 'Тапсырыс рәсімделді',
  'order.success.body':
      'Сатып алғаныңызға рахмет! Тапсырыс мәліметтері — төменде.',
  'order.success.orderNumber': 'Тапсырыс нөмірі',
  'order.success.total': 'Сомасы',
  'order.success.itemCount': 'Тауарлар',
  'order.success.paymentStatus': 'Төлем күйі',
  'order.success.viewOrder': 'Тапсырысты қарау',
  'order.success.continueShopping': 'Сатып алуды жалғастыру',

  'error.ORDER_NOT_FOUND': 'Тапсырыс табылмады',
  'error.INVALID_ORDER_ID': 'Тапсырыс нөмірі қате',
  'error.USER_NOT_FOUND': 'Пайдаланушы табылмады',
  'error.INTERNAL_ERROR': 'Сервер қатесі. Кейінірек қайталап көріңіз.',

  // ---- F6B: seller offers + inventory ----
  'seller.offers.title': 'Ұсыныстар',
  'seller.offers.add': 'Ұсыныс қосу',
  'seller.offers.edit': 'Ұсынысты өзгерту',
  'seller.offers.editUnavailable': 'Ұсынысты ашу мүмкін болмады',
  'seller.offers.searchHint': 'Тауар немесе SKU бойынша іздеу',
  'seller.offers.noResults': 'Ештеңе табылмады',
  'seller.offers.empty.title': 'Әзірге ұсыныстарыңыз жоқ',
  'seller.offers.empty.body': 'Каталогтағы тауарға ұсыныс қосыңыз',
  'seller.offers.created': 'Ұсыныс қосылды',
  'seller.offers.saved': 'Өзгерістер сақталды',
  'seller.offers.activate': 'Белсендіру',
  'seller.offers.deactivate': 'Өшіру',
  'seller.offers.status.active': 'Белсенді',
  'seller.offers.status.inactive': 'Белсенді емес',
  'seller.offers.filter.all': 'Барлығы',
  'seller.offers.filter.active': 'Белсенді',
  'seller.offers.filter.inactive': 'Белсенді емес',
  'seller.offers.filter.lowStock': 'Азайып барады',
  'seller.offers.stockN': 'Қоймада: {n}',
  'seller.offers.deliveryN': 'Жеткізу: {n} күн',
  'seller.offers.reservedN': 'Резервте: {n}',
  'seller.offers.field.sku': 'SKU (артикул)',
  'seller.offers.field.price': 'Бағасы, ₸',
  'seller.offers.field.oldPrice': 'Ескі бағасы, ₸',
  'seller.offers.field.oldPriceHint':
      'Міндетті емес. Сызылған бағаны алып тастау үшін бос қалдырыңыз.',
  'seller.offers.field.deliveryDays': 'Жеткізу мерзімі, күн',
  'seller.offers.field.stock': 'Қалдық, дана',
  'seller.offers.validation.productRequired': 'Тауарды таңдаңыз',
  'seller.offers.validation.skuRequired': 'SKU көрсетіңіз',
  'seller.offers.validation.priceInvalid':
      'Дұрыс соманы енгізіңіз, мысалы 250000 немесе 250000.00',
  'seller.offers.validation.deliveryInvalid':
      'Жеткізу мерзімі — 0 немесе одан көп',
  'seller.offers.validation.stockInvalid': 'Қалдық — 0 немесе одан көп',
  'seller.offers.productSelect.title': 'Тауар таңдау',
  'seller.offers.productSelect.searchHint': 'Тауарды іздеу',
  'seller.offers.productSelect.empty': 'Тауарлар табылмады',
  'seller.offers.productSelect.prompt':
      'Ұсыныс қосатын тауарды каталогтан таңдаңыз',
  'seller.offers.productSelect.cta': 'Тауарды таңдау',
  'seller.offers.productSelect.change': 'Өзгерту',

  'seller.inventory.title': 'Қалдықтар',
  'seller.inventory.empty.title': 'Қоймада позициялар жоқ',
  'seller.inventory.empty.body': 'Қалдықтарды басқару үшін ұсыныстар қосыңыз',
  'seller.inventory.availableN': 'Қолжетімді: {n}',
  'seller.inventory.reservedN': 'Резервте: {n}',
  'seller.inventory.lowStock': 'Азайып барады',
  'seller.inventory.lowStockBanner': 'Азайып бара жатқан позициялар: {n}',
  'seller.inventory.edit': 'Өзгерту',
  'seller.inventory.editTitle': 'Қалдықты өзгерту',
  'seller.inventory.field.available': 'Қолжетімді саны',
  'seller.inventory.reservedNote':
      '{n} дана белсенді тапсырыстарда — оларды алып тастауға болмайды.',
  'seller.inventory.validation.quantity': 'Саны — 0 немесе одан көп',

  'error.INVALID_PRICE': 'Баға қате',
  'error.INVALID_OLD_PRICE': 'Ескі баға қате',
  'error.INVALID_DELIVERY_DAYS': 'Жеткізу мерзімі қате',
  'error.INVALID_STOCK': 'Қалдық қате',
  'error.INVALID_STATUS': 'Мәртебе қате',
  'error.SKU_ALREADY_EXISTS': 'Сізде мұндай SKU бар ұсыныс бұрыннан бар',
  'error.OFFER_NOT_FOUND': 'Ұсыныс табылмады',
  'error.INVALID_OFFER_ID': 'Ұсыныс идентификаторы қате',

  // ---- F6C: seller orders ----
  'seller.orders.title': 'Тапсырыстар',
  'seller.orders.detailTitle': 'Тапсырыс',
  'seller.orders.empty.title': 'Әзірге тапсырыс жоқ',
  'seller.orders.empty.body':
      'Мұнда сіздің тауарларыңыз бар тапсырыстар көрінеді',
  'seller.orders.itemsN': '{n} поз.',
  'seller.orders.gross': 'Позицияларыңыздың сомасы',
  'seller.orders.commission': 'Маркетплейс комиссиясы',
  'seller.orders.net': 'Есептелетін сома',
  'seller.orders.items': 'Сіздің позицияларыңыз',
  'seller.orders.delivery': 'Жеткізу мекенжайы',
  'seller.orders.yourLinesOnly':
      'Осы тапсырыстың тек сіздің позицияларыңыз көрсетілген',
  'seller.orders.lineCommission': 'комиссия {v}',
  'seller.orders.lineNet': 'сізге {v}',

  // ---- F6D: seller finance + payouts ----
  'seller.finance.title': 'Қаржы',
  'seller.finance.available': 'Шығаруға қолжетімді',
  'seller.finance.availableNote': 'Бұл қаражатты шығаруға болады.',
  'seller.finance.pending': 'Күтуде',
  'seller.finance.pendingNote': 'Әлі бекітілмеген — шығаруға болмайды.',
  'seller.finance.breakdown': 'Есеп',
  'seller.finance.grossSales': 'Сатылымдар (жалпы)',
  'seller.finance.commission': 'Маркетплейс комиссиясы',
  'seller.finance.net': 'Сіздің табысыңыз (таза)',
  'seller.finance.paidOut': 'Барлығы шығарылды',
  'seller.finance.viewPayouts': 'Төлемдер тарихы',

  'payout.title': 'Төлемдер',
  'payout.empty.title': 'Әзірге төлем жоқ',
  'payout.empty.body': 'Қолжетімді қаражатты шығаруды сұраңыз',
  'payout.availableToWithdraw': 'Шығаруға қолжетімді',
  'payout.requestedOn': '{date} сұралды',
  'payout.processedOn': '{date} өңделді',
  'payout.status.pending': 'Күтуде',
  'payout.status.processing': 'Өңделуде',
  'payout.status.paid': 'Төленді',
  'payout.status.rejected': 'Қабылданбады',
  'payout.status.unknown': '—',
  'payout.request.title': 'Төлемді сұрау',
  'payout.request.submit': 'Сұрау',
  'payout.request.submitted': 'Төлем сұрауы жіберілді',
  'payout.request.field.amount': 'Сома, ₸',
  'payout.request.availableHint': 'Қолжетімді: {v}',
  'payout.request.pendingNote': 'Күтудегі қаражатты шығаруға болмайды.',
  'payout.request.error.positive': 'Нөлден үлкен соманы енгізіңіз',
  'payout.request.error.overAvailable': 'Сома қолжетімді балансынан асып тұр',

  'error.INSUFFICIENT_AVAILABLE_BALANCE':
      'Шығаруға қолжетімді қаражат жеткіліксіз',
};
